USE [db_Hero_MVC_AdoNet]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SecretInsert]
	@Name VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO Secrets
		([Name])
	VALUES
		(@Name)
	OPTION (MAXDOP 2)
	SELECT CAST(SCOPE_IDENTITY() AS INT)
END
