USE [db_Hero_MVC_AdoNet]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SecretUpdate]
	@SecretId INT,
	@Name VARCHAR(50)
AS
BEGIN
	UPDATE Secrets 
	SET 
		Name = @Name
	WHERE SecretId = @SecretId
	OPTION (MAXDOP 2)
END