USE [db_Hero_MVC_AdoNet]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[WeaponDelete]
	@WeaponId INT
AS
BEGIN
	DELETE Weapons 
	WHERE WeaponId = @WeaponId
	OPTION (MAXDOP 2)
END