USE [db_Hero_MVC_AdoNet]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[MovieGetById]
	@MovieId int
AS
BEGIN
	SELECT TOP 1 * 
		FROM Movies
		WHERE MovieId = @MovieId
	ORDER BY 1 DESC 
	OPTION (MAXDOP 2)
END
