USE [db_Hero_MVC_AdoNet]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[MovieInsert]
	@Name VARCHAR(50),
	@Rate INT
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO Movies
		([Name], [Rate])
	VALUES
		(@Name, @Rate)
	OPTION (MAXDOP 2)
	SELECT CAST(SCOPE_IDENTITY() AS INT)
END
