USE [db_Hero_MVC_AdoNet]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[VerifyRelationWithWeapons]
	@HeroId INT
AS
BEGIN
	SELECT COUNT(WeaponId) 
	FROM Weapons 
	WHERE HeroId = @HeroId
END